package com.klist.chatbot.chat.presentation.error;

public enum InternalChatApiErrorCode {
    UNAUTHORIZED,
    INTERNAL_AUTH_NOT_CONFIGURED,
    REQUEST_IN_PROGRESS,
    REQUEST_ID_CONFLICT,
    INVALID_REQUEST,
    CHAT_QUERY_TIMEOUT,
    CHAT_PROCESSING_UNAVAILABLE,
    CHAT_PROCESSING_FAILED,
    STT_INVALID_FILE,
    STT_FILE_TOO_LARGE,
    STT_TIMEOUT,
    STT_EMPTY_RESULT,
    STT_UNAVAILABLE,
    INTERNAL_ERROR
}
