CREATE TABLE tourist_spot_index_failure (
    tourist_spot_index_failure_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    tourist_spot_id BIGINT NOT NULL,
    operation VARCHAR(30) NOT NULL,
    target_index VARCHAR(255) NOT NULL,
    failure_type VARCHAR(30) NOT NULL,
    failure_message VARCHAR(1000) NOT NULL,
    status VARCHAR(20) NOT NULL,
    retry_count INTEGER NOT NULL DEFAULT 0,
    next_retry_at TIMESTAMP,
    last_failed_at TIMESTAMP NOT NULL,
    version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT pk_tourist_spot_index_failure
        PRIMARY KEY (tourist_spot_index_failure_id),
    CONSTRAINT uk_tourist_spot_index_failure_target
        UNIQUE (tourist_spot_id, operation, target_index),
    CONSTRAINT ck_tourist_spot_index_failure_retry_count
        CHECK (retry_count >= 0)
);

CREATE INDEX idx_tourist_spot_index_failure_due
    ON tourist_spot_index_failure (status, next_retry_at);

CREATE INDEX idx_tourist_spot_index_failure_target_index
    ON tourist_spot_index_failure (target_index);
